### ISSUE TITLE
Unable to get hello world running

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-hipe#3]
Hi tried a helloworld with hipe and had the following problems:

* The generated code had calls such as `null.MyCorrPackage...` at many locations.  After deleting the `null.` manually the code compiled.
* The generated code contained `<<src_package>>` and `<<trg_package>>` at many locations.  I had to replace these parts with my actual source and target packages.  Not sure if this is what is supposed to happen but after that the code compiled.
* When everything finally compiled I got the following runtime error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void hipe.engine.HiPEContentAdapter.<init>(org.eclipse.emf.ecore.resource.ResourceSet, hipe.engine.IHiPEEngine)'
	at org.emoflon.ibex.gt.hipe.runtime.HiPEGTEngine.initEngine(HiPEGTEngine.java:295)
	at org.emoflon.ibex.gt.hipe.runtime.HiPEGTEngine.monitor(HiPEGTEngine.java:259)
	at org.emoflon.ibex.tgg.runtime.hipe.HiPETGGEngine.monitor(HiPETGGEngine.java:174)
```
After some checking I believe this method really does not exist.  Something must be wrong with the different versions of the supplied jars.
* I did not install democles and got a series of errors as the project is created with democles dependencies.  It might make sense to make the new project wizard democles/hipe aware.

**Comment by anthonyanjorin** [comment]
[hipe.zip](https://github.com/eMoflon/emoflon-ibex-hipe/files/4870656/hipe.zip)
